const {Schema,model}=require('mongoose');
const { count } = require('./user');

const OrdenSchema = new Schema({
    //location data
    //laituds
    //origne
    latitudOrigen: {
        type: Float32Array,
        require: true
    },
    longitudOrigen: {
        type: Float32Array,
        require: true
    },
    //destino
    latitudDestino: {
        type: Float32Array,
        require: true
    },
    longitudDestino: {
        type: Float32Array,
        require: true
    },
    Colonia: {
        type: String,
        require: true
    },
    //personal data
    //destino
    CalleDestino: {
        type: String,
        require: true
    },
    codigoPostalDestino: {
        type: Int16Array,
        require: true
    },
    NumeroInterioDestino: {
        type: Int16Array,
        require: true
    },

    NumeroExteriorDestino: Int16Array,

    LocalidadDestino: {
        type: String,
        require: true
    },
    //Origen
    CalleOrigen: {
        type: String,
        require: true
    },
    codigoPostalOrigen: {
        type: Int16Array,
        require: true
    },
    NumeroInterioOrigen: {
        type: Int16Array,
        require: true
    },

    NumeroExteriorOrigen: Int16Array,

    LocalidadOrigen: {
        type: String,
        require: true
    },

    //general data
    Pesos: {
        type: Array,
        require: true
    },

    Estatus: {
        type: String,
        require: true
    },

    //autogenerated data
    Id: Int16Array,
    tamaño: String,
    numeroProductos: Int16Array,

}, {
    timestamps: true
})

//functions
function sumWights (Array) {
    let total = 0;
    for (let number of Array){
        total += number;
    }
    return total;
}

//inicialization auto generated data
OrdenSchema.methods.countArticles = function() {
    this.numeroProductos = this.Pesos.length;
    
    const totalWight = sumWights(this.Pesos);
    
    let weight = '';
    if( totalWight <= 5){
        weight = 'S';
    } else if(totalWight <= 15){
        weight = 'M';
    } else if(totalWight <= 25){
        weight = 'L'
    } else {
        weight = 'E';
    }
    this.tamaño = weight;
    this.Estatus = 'creado';
}

module.exports=model('OrdenCompra',OrdenSchema); 