const {Schema,model}=require('mongoose');
const { count } = require('./user');

const OrdenSchema = new Schema({
    //location data
    //laituds
    //origne
    latitudOrigen: {
        type: Number,
        require: true
    },
    longitudOrigen: {
        type: Number,
        require: true
    },
    //destino
    latitudDestino: {
        type: Number,
        require: true
    },
    longitudDestino: {
        type: Number,
        require: true
    },
    Colonia: {
        type: String,
        require: true
    },
    //personal data
    //destino
    CalleDestino: {
        type: String,
        require: true
    },
    codigoPostalDestino: {
        type: Number,
        require: true
    },
    NumeroInterioDestino: {
        type: Number,
        require: true
    },

    NumeroExteriorDestino: Number,

    LocalidadDestino: {
        type: String,
        require: true
    },
    //Origen
    CalleOrigen: {
        type: String,
        require: true
    },
    codigoPostalOrigen: {
        type: Number,
        require: true
    },
    NumeroInterioOrigen: {
        type: Number,
        require: true
    },

    NumeroExteriorOrigen: Number,

    LocalidadOrigen: {
        type: String,
        require: true
    },

    //general data
    Pesos: {
        type: Array,
        require: true
    },

    Estatus: String,

    //autogenerated data
    //Id: Number,
    tamaño: String,
    numeroProductos: Number,
    user:{
        type: String,
        require:true
    }

}, {
    timestamps: true
})

//functions
function sumWeights (Array) {
    let total = 0;
    for (let number of Array){
        total += number;
    }
    return total;
}

module.exports=model('OrdenCompra',OrdenSchema); 